"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['frequency.py']
DATA_FILES = [('testmap.json')]
OPTIONS = {
    'argv_emulation': True,
    'packages': ['pygame','json','math']
        }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
